webapp/library/urls.py
"""
URL configuration for library of webapp project.
"""

from django.urls import path
from . import views


app_name = "library"

urlpatterns = [
    path('all_books',
         views.book_catalog,
         name='book_catalog'),
    path('book/<int:book_id>/',
         views.book_info,
         name='book_info'),
    path('my_books',
         views.get_my_books,
         name='my_books'),
    path('change_book/<int:book_id>/',
         views.change_book_info,
         name='change_book'),
    path('add_book',
         views.select_category,
         name='select_category'),
    path('add_book/<int:book_category_id>',
         views.add_book,
         name='add_book'),
    path('select_reader_for_book_issuer',
         views.select_reader_for_book_issuer,
         name='select_reader'),
    path('reader_books/<int:reader_id>',
         views.get_reader_books,
         name='reader_books'),
    path('give_fiction_book/<int:reader_id>',
         views.give_fiction_book,
         name='give_fiction_book'),
    path('select_class_for_book_issuer',
         views.select_class_for_book_issuer,
         name='select_class'),
    path('class_books/<int:class_id>',
         views.get_class_books,
         name='class_books'),
    path('give_study_book/<int:class_id>',
         views.give_study_book,
         name='give_study_book'),
    path('generate_csv_report/<int:class_id>',
         views.generate_csv_report,
         name='generate_csv_report'),
]

webapp/users/urls.py
"""
URL configuration for users of webapp project.
"""

from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/', views.create_user, name='create_user'),
    path('profile/', views.profile_view, name='profile'),
]

webapp/webapp/urls.py
"""
URL configuration for webapp project.
"""

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import views
from . import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('library/', include('library.urls', namespace="library")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

webapp/library/forms.py
"""
Library's forms for webapp project.
"""

from django.forms import Form, ModelChoiceField, CharField, IntegerField
from django.forms import Select, TextInput, ImageField, Textarea, FileInput
from django.forms import DateField, DateInput
from .models import Book_Category


class BookCategoryForm(Form):
    """
    Форма выбора категории литературы
    """
    book_category = ModelChoiceField(
        queryset=Book_Category.objects.all(),
        to_field_name="name_category",
        widget=Select(
            attrs={'class': 'form-select form-select-lg text-center'}
        )
    )


class BookForm(Form):
    """
    Форма добавления художественной книги
    """
    book_name = CharField(
        label='Наименование',
        min_length=2,
        widget=TextInput(
            attrs={
                'class': 'form-control border border-primary',
                'placeholder': 'Наименование книги'
            }
        )
    )
    book_author = CharField(
        label='Автор',
        widget=TextInput(
            attrs={
                'class': 'form-control border border-primary',
                'placeholder': 'Автор'
            }
        )
    )
    year_publish = IntegerField(
        label='Год издания',
        widget=TextInput(
            attrs={
                'class': 'form-control border border-primary',
                'placeholder': 'Год издания'
            }
        )
    )
    book_description = CharField(
        label='Краткое описание',
        widget=Textarea(
            attrs={
                'class': 'form-control border border-primary',
                'rows': '4',
                'placeholder': 'Краткое описание'
            }
        )
    )
    num_copies = IntegerField(
        label='Кол-во экземпляров',
        widget=TextInput(
            attrs={
                'class': 'form-control border border-primary',
                'placeholder': 'Кол-во экземпляров'
            }
        )
    )
    book_study_class = IntegerField(
        label='Класс изучения',
        required=False,
        widget=TextInput(
            attrs={
                'class': 'form-control border border-primary',
                'placeholder': 'Класс изучения'
            }
        )
    )
    book_image = ImageField(
        label='Изображение',
        required=False,
        widget=FileInput(
            attrs={
                'class': 'form-control',
                'type': 'file',
                'name': 'book_image'
            }
        )
    )


class GiveFictionBookForm(Form):
    """
    Форма выдачи художественной литературы
    """
    issue_day = DateField(
        label='Дата выдачи',
        widget=DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control border border-primary text-center',
                'placeholder': 'Дата выдачи'
            }
        )
    )
    planned_return_day = DateField(
        label='Предполагаемый день возврата',
        widget=DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control border border-primary text-center',
                'placeholder': 'Предполагаемый день возврата'
            }
        )
    )


class GiveStudyBookForm(Form):
    """
    Форма выдачи учебной литературы
    """
    issue_day = DateField(
        label='Дата выдачи',
        widget=DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control border border-primary text-center',
                'placeholder': 'Дата выдачи'
            }
        )
    )
    planned_return_day = DateField(
        label='Предполагаемый день возврата',
        widget=DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control border border-primary text-center',
                'placeholder': 'Предполагаемый день возврата'
            }
        )
    )

webapp/library/views.py
"""
Library's views for webapp project.
"""
import codecs
import csv
import os
from datetime import datetime, timedelta
from django.db.models import Count, F, Q, Subquery, OuterRef, Sum
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group, User
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator
from django.contrib import messages
from django.conf import settings
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Book, Book_Category, School_Class
from .models import Store_Fiction_Book, Store_Study_Book
from .forms import BookForm, BookCategoryForm
from .forms import GiveFictionBookForm, GiveStudyBookForm


def check_group(request, group_name) -> bool:
    """
    Проверка, что пользователь принадлежит к группе Reader

    :param group_name: имя группы
    """
    user = request.user
    group = Group.objects.get(name=group_name)
    if user.groups.filter(name=group.name).exists():
        return True
    return False


def generate_csv_report(request, class_id):
    """
    Формирует CSV-отчет по данным из таблицы Store_Study_Book для класса.
    """
    class_info = School_Class.objects.get(pk=class_id)
    csv_file_name = f'Список книг для {class_info.class_number} {class_info.class_letter} класса.csv'
    with codecs.open(csv_file_name, 'w', 'cp1251') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow([
            'Название книги',
            'Автор',
            'Кол-во книг',
            'Дата выдачи',
            'Планируемая дата возврата',
        ])

        books = Store_Study_Book.objects.filter(
            school_class=class_id,
            return_day__isnull=True,
            status_store=True
        )
        for book in books:
            writer.writerow([
                book.book.book_name,
                book.book.book_author,
                book.num_books,
                book.issue_day,
                book.planned_return_day,
            ])

    return HttpResponse(open(csv_file_name, 'rb').read(), content_type='text/csv')


@login_required(login_url='/home')
def book_catalog(request):
    """
    Каталог книг
    """
    if check_group(request, group_name='Reader'):
        all_books = Book.objects.filter(book_category_id=1).order_by('-id')
    else:
        all_books = Book.objects.all().order_by('-id')

    search_term = ''
    # Сортировка по наименованию книги
    if 'book_name_asc' in request.GET:
        all_books = all_books.order_by('book_name')
    if 'book_name_desc' in request.GET:
        all_books = all_books.order_by('-book_name')
    # Сортировка по году публикации книги
    if 'year_publish_asc' in request.GET:
        all_books = all_books.order_by('year_publish')
    if 'year_publish_desc' in request.GET:
        all_books = all_books.order_by('-year_publish')
    # Поиск по наименованию, автору и году публикации
    if 'search' in request.GET:
        search_term = request.GET['search']
        all_books = (all_books.filter(book_name__icontains=search_term) |
                     all_books.filter(book_author__icontains=search_term) |
                     all_books.filter(year_publish__icontains=search_term))

    # Пагинация
    paginator = Paginator(all_books, 4)
    page = request.GET.get('page')
    books = paginator.get_page(page)
    get_dict_copy = request.GET.copy()
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()

    context = {
        'books': books,
        'params': params,
        'search_term': search_term,
    }
    return render(request, 'library/books.html', context)


@login_required(login_url='/home')
def book_info(request, book_id):
    """
    Информация по выбранной книге

    :param book_id: id книги
    """
    try:
        book = get_object_or_404(Book, pk=book_id)
    except Book.DoesNotExist:
        messages.error(request,
                       'Книга не найдена!',
                       extra_tags='''alert alert-warning'''
                                  '''alert-dismissible fade show'''
                       )
        return redirect('library:book_catalog')

    context = {
        'book': book
    }
    return render(request, 'library/book_info.html', context)


@login_required(login_url='/home')
def get_my_books(request):
    """
    Книги пользователя (мои книги)
    """
    current_user = request.user
    user_books = Store_Fiction_Book.objects.filter(
        reader_id=current_user.id
    ).order_by('planned_return_day')

    search_term = ''
    # Сортировка по плановой дате возврата
    if 'return_day_asc' in request.GET:
        user_books = user_books.order_by('planned_return_day')
    if 'return_day_desc' in request.GET:
        user_books = user_books.order_by('-planned_return_day')
    # Поиск по наименованию книги
    if 'search' in request.GET:
        search_term = request.GET['search']
        user_books = user_books.filter(
           book__book_name__icontains=search_term
        )

    context = {
        'user_books': user_books,
        'search_term': search_term,
        'today': timezone.now().date()
    }

    return render(request, 'library/my_books.html', context)


@permission_required('library.add_book', login_url='/library/all_books')
def select_category(request):
    """
    Выбор категории литературы перед добавление новой книги
    """
    if request.method == 'POST':
        form = BookCategoryForm(data=request.POST)
        if form.is_valid():
            book_category = Book_Category.objects.get(
                name_category=str(form.cleaned_data.get('book_category'))
            )
            if book_category:
                return redirect('library:add_book', book_category.id)
            messages.error(request,
                           f'''Категория "{book_category}" не найдена,'''
                           f''' обратитесь к администратору!''',
                           extra_tags='''alert alert-warning'''
                                      '''alert-dismissible fade show''')
            return redirect('library:select_category')
    form = BookCategoryForm()

    return render(request, 'library/select_category.html', {'form': form})


@permission_required('library.add_book', login_url='/library/all_books')
def add_book(request, book_category_id):
    """
    Добавление новой книги
    """
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book_name = form.cleaned_data.get('book_name')
            book_author = form.cleaned_data.get('book_author')
            year_publish = form.cleaned_data.get('year_publish')
            book_description = form.cleaned_data.get('book_description')
            num_copies = form.cleaned_data.get('num_copies')
            book_study_class = form.cleaned_data.get('book_study_class')
            if form.cleaned_data.get('book_image'):
                book_image = request.FILES['book_image']
            else:
                book_image = None

            Book.objects.create(
                book_category_id=book_category_id,
                book_name=book_name,
                book_author=book_author,
                year_publish=year_publish,
                book_description=book_description,
                num_copies=num_copies,
                book_study_class=book_study_class,
                book_image=book_image
            )

            book_category = get_object_or_404(
                Book_Category, pk=book_category_id
            )
            messages.success(
                request,
                f'{book_category.name_category} литература успешно добавлена!',
                extra_tags='alert alert-success alert-dismissible fade show'
            )
            return redirect('library:book_catalog')
    form = BookForm()
    context = {
        'form': form,
        'book_category_id': book_category_id
    }
    return render(request, 'library/add_book.html', context)


@permission_required(['library.change_book', 'library.delete_book'],
                     login_url='/library/all_books')
def change_book_info(request, book_id):
    """
    Изменение информации о имеющейся книги или удаление ее
    """
    try:
        book = get_object_or_404(Book, pk=book_id)
    except Book.DoesNotExist:
        messages.error(request,
                       'Книга не найдена!',
                       extra_tags='''alert alert-warning'''
                                  '''alert-dismissible fade show'''
                       )
        return redirect('library:book_catalog')

    if request.method == 'POST' and 'change' in request.POST:
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book_name = form.cleaned_data.get('book_name')
            book_author = form.cleaned_data.get('book_author')
            year_publish = form.cleaned_data.get('year_publish')
            book_description = form.cleaned_data.get('book_description')
            num_copies = form.cleaned_data.get('num_copies')
            book_study_class = form.cleaned_data.get('book_study_class')
            if form.cleaned_data.get('book_image'):
                book_image = request.FILES['book_image']
                FileSystemStorage(
                    location=os.path.join(settings.MEDIA_ROOT, 'library')
                ).save(book_image.name, book_image)
                book_image = f'library/{book_image}'
            else:
                book_image = book.book_image

            Book.objects.filter(id=book_id).update(
                book_name=book_name,
                book_author=book_author,
                year_publish=year_publish,
                book_description=book_description,
                num_copies=num_copies,

webapp/library/templates/library/books.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/table_style.css' %}">
{% endblock custom_css %}

{% load auth_extras %}

{% block content %}
    <div class="container">
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-lg-12 mb-2">
                <h1 class="text-center mb-3">Каталог книг</h1>
                <div>
                    <div class="card mb-6 border-secondary" style="height: 610px;">
                        <div class="card-header">
                            <form class="form-inline">
                                <div class="btn-group">
                                    <a class="btn btn-{% if 'book_name_asc' in request.GET %}warning{% else %}primary{% endif %} mb-2" href="?book_name_asc=True" role="button"><i class="fas fa-sort-alpha-down"></i></a>
                                    <a class="btn mb-2 disabled" role="button"> По наименованию </a>
                                    <a class="btn btn-{% if 'book_name_desc' in request.GET %}warning{% else %}primary{% endif %} mr-sm-2 mb-2" href="?book_name_desc=True" role="button"><i class="fas fa-sort-alpha-up"></i></a>
                                </div>
                                <div class="btn-group">
                                    <a class="btn btn-{% if 'year_publish_asc' in request.GET %}warning{% else %}primary{% endif %} mb-2" href="?year_publish_asc=True" role="button"><i class="fas fa-sort-numeric-down"></i></a>
                                    <a class="btn mb-2 disabled" role="button"> По году издания </a>
                                    <a class="btn btn-{% if 'year_publish_desc' in request.GET %}warning{% else %}primary{% endif %} mr-sm-2 mb-2" href="?year_publish_desc=True" role="button"><i class="fas fa-sort-numeric-up"></i></a>
                                </div>
                                <div class="form-group ml-auto mr-sm-2 mb-2">
                                    <input type="search" class="form-control" name="search" placeholder="Поиск" value={{ search_term }}>
                                </div>
                                <button type="submit" class="btn btn-primary mb-2"><i class="fas fa-search"></i></button>
                            </form>
                        </div>
                        <div class="card-body" style="max-height: 515px;">
                            <table class="table table-hover table-bordered" id="books">
                                <thead class="table-light">
                                    <tr>
                                        <th class="align-middle">Фото</th>
                                        <th class="align-middle" data-type="string">Наименование книги</th>
                                        <th class="align-middle" data-type="string">Автор</th>
                                        <th class="align-middle" data-type="number">Год издания</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for book in books %}
                                        <tr>
                                            <td class="align-middle">
                                                {% if book.book_image %}
                                                    <img class="book_image" src="{{ book.book_image.url }}">
                                                {% endif %}
                                            </td>
                                            <td class="align-middle">
                                                {% if request.user|is_group:"Reader" %}
                                                    <a href="{% url 'library:book_info' book.id %}">{{ book.book_name }}</a>
                                                {% else %}
                                                    <a href="{% url 'library:change_book' book.id %}">{{ book.book_name }}</a>
                                                {% endif %}
                                            </td>
                                            <td class="align-middle">
                                                {{ book.book_author }}
                                            </td>
                                            <td class="align-middle">
                                                {{ book.year_publish }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                            {% if books.paginator.num_pages > 1 %}
                                <nav class="mt-3">
                                    <ul class="pagination">
                                        <li class="page-item">
                                        {% if books.has_previous %}
                                            <a class="page-link" href="?page={{ books.previous_page_number }}&{{ params }}" aria-label="Предыдущая">
                                        {% else %}
                                            <a class="page-link" aria-label="Предыдущая">
                                        {% endif %}
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                        
                                        {% for num_page in books.paginator.page_range %}
                                            {% if num_page == books.number %}
                                                <li class="page-item active">
                                            {% else %}
                                                <li class="page-item">
                                            {% endif %}
                                                    <a class="page-link" href="?page={{ num_page }}&{{ params }}">{{num_page}}</a>
                                                </li>
                                        {% endfor %}
            
                                        <li class="page-item">
                                        {% if books.has_next %}
                                            <a class="page-link" href="?page={{ books.next_page_number }}&{{ params }}" aria-label="Следующая">
                                        {% else %}
                                            <a class="page-link" aria-label="Следующая">
                                        {% endif %}
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

webapp/library/templates/library/choose_class.html
{% extends 'base.html' %}

{% load static %}

{% load auth_extras %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <h3 class="text-center mb-3">Выберите класс:</h3>
                {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}

                <form class="form-inline">
                    <div class="form-group ml-auto mr-sm-2 mb-2">
                        <input type="search" class="form-control" name="search" placeholder="Поиск" value={{ search_term }}>
                    </div>
                    <button type="submit" class="btn btn-primary mb-2"><i class="fas fa-search"></i></button>
                </form>
                
                <div class="list-group" style="max-height: 575px; overflow: auto;">
                    {% for class in class_list %}
                        <li class="list-group-item d-flex justify-content-between list-group-item-action">
                            <div class="ms-2 me-auto">
                                <div class="fw-bold">
                                    {{ class.class_number }} класс
                                    {% if class.num_active_books != None %}
                                        <span class="badge text-bg-success rounded-pill">{{ class.num_active_books }}</span>
                                    {% endif %}
                                    {% if class.num_overdue_books != None %}
                                        <span class="badge text-bg-danger rounded-pill">{{ class.num_overdue_books }}</span>
                                    {% endif %}
                                </div>
                                {{ class.class_letter }}
                            </div>
                            <a href="{% url 'library:class_books' class.id %}"><i class="fas fa-arrow-right float-right btn btn-secondary"></i></a>
                        </li>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

webapp/library/templates/library/choose_reader.html
{% extends 'base.html' %}

{% load static %}

{% load auth_extras %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <h3 class="text-center mb-3">Выберите читателя:</h3>
                {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}

                <form class="form-inline">
                    <div class="form-group ml-auto mr-sm-2 mb-2">
                        <input type="search" class="form-control" name="search" placeholder="Поиск" value={{ search_term }}>
                    </div>
                    <button type="submit" class="btn btn-primary mb-2"><i class="fas fa-search"></i></button>
                </form>
                
                <div class="list-group list-group-numbered" style="max-height: 575px; overflow: auto;">
                    {% for reader in reader_list %}
                        <li class="list-group-item d-flex justify-content-between list-group-item-action">
                            <div class="ms-2 me-auto">
                                <div class="fw-bold">
                                    {{ reader.last_name }} {{ reader.first_name }}
                                    {% if reader.num_active_books != 0 %}
                                        <span class="badge text-bg-success rounded-pill">{{ reader.num_active_books }}</span>
                                    {% endif %}
                                    {% if reader.num_overdue_books != 0 %}
                                        <span class="badge text-bg-danger rounded-pill">{{ reader.num_overdue_books }}</span>
                                    {% endif %}
                                </div>
                                Логин: {{ reader.username }}, почта: {{ reader.email }}
                            </div>
                            
                            <a href="{% url 'library:reader_books' reader.id %}"><i class="fas fa-arrow-right float-right btn btn-secondary"></i></a>
                        </li>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

webapp/library/templates/library/select_category.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/books_style.css' %}">
{% endblock custom_css %}

{% block content %}
    <div class="container text-center">
        
        <div class="row justify-content-center">
            <div class="col-md-6 mt-5 mx-auto p-5"> 
                {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="card border-secondary text-center shadow-sm">
                    <h5 class="card-header">Выберите категорию литературы:</h5>
                    <div class="col-md-7 align-self-center">
                        <div class="card-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    {{ form.book_category }}
                                </div>
                                <div class="row">
                                    <button type="submit" class="btn btn-primary">Продолжить</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}