webapp/library/urls.py
"""
URL configuration for library of webapp project.
"""

from django.urls import path
from . import views


app_name = "library"

urlpatterns = [
    path('all_books',
         views.book_catalog,
         name='book_catalog'),
    path('book/<int:book_id>/',
         views.book_info,
         name='book_info'),
    path('my_books',
         views.get_my_books,
         name='my_books'),
    path('change_book/<int:book_id>/',
         views.change_book_info,
         name='change_book'),
    path('add_book',
         views.select_category,
         name='select_category'),
    path('add_book/<int:book_category_id>',
         views.add_book,
         name='add_book'),
    path('select_reader_for_book_issuer',
         views.select_reader_for_book_issuer,
         name='select_reader'),
    path('reader_books/<int:reader_id>',
         views.get_reader_books,
         name='reader_books'),
    path('give_fiction_book/<int:reader_id>',
         views.give_fiction_book,
         name='give_fiction_book'),
    path('select_class_for_book_issuer',
         views.select_class_for_book_issuer,
         name='select_class'),
    path('class_books/<int:class_id>',
         views.get_class_books,
         name='class_books'),
    path('give_study_book/<int:class_id>',
         views.give_study_book,
         name='give_study_book'),
    path('generate_csv_report/<int:class_id>',
         views.generate_csv_report,
         name='generate_csv_report'),
]

webapp/users/urls.py
"""
URL configuration for users of webapp project.
"""

from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/', views.create_user, name='create_user'),
    path('profile/', views.profile_view, name='profile'),
]

webapp/webapp/urls.py
"""
URL configuration for webapp project.
"""

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import views
from . import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('library/', include('library.urls', namespace="library")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

webapp/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Electronic library 83</title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

        {% block custom_css %}
        {% endblock custom_css %}

    </head>

    <body>
        {% include 'navbar.html' %}

        {% block content %}
        {% endblock content %}

        <!-- All javascript files goes under here    -->
        <script src="https://code.jquery.com/jquery-3.7.0.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>

</html>

webapp/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/home_style.css' %}">
{% endblock custom_css %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div id="home-content">
                    <h1>Информационная система электронной библиотеки 83</h1>
                    <h3>Библиотека, в которой не скучно!</h3>
                    <hr>
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-light btn-lg" href="{% url 'library:book_catalog' %}" role="button">Найти книгу!</a>
                    {% else %}
                        <a class="btn btn-light btn-lg" href="{% url 'users:login_user' %}" role="button">Найти книгу!</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

webapp/templates/navbar.html
{% load static %}

{% load auth_extras %}

<nav class="navbar navbar-expand-sm navbar-light bg-light mb-4">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'img/label_small.png' %}" alt="Logo" width="40" height="40">
    </a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">

        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}"> Главная <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library:book_catalog' %}">Каталог книг</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login_user' %}">Каталог книг</a>
                </li>
            {% endif %}
            {% if request.user|is_group:"Reader" %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library:my_books' %}">Мои книги</a>
                </li>
            {% elif request.user|is_group:"Librarian" %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library:select_category' %}">Добавить книгу</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library:select_reader' %}">Учет художественной литературы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'library:select_class' %}">Учет учебной литературы</a>
                </li>
            {% endif %}
        </ul>
        <div class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                {% if user.is_superuser %}
                    <a class="nav-link" href="/admin/">Администрирование</a>
                {% else %}
                    <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
                {% endif %}
                <a class="nav-link" href="{% url 'users:logout_user' %}">Выйти</a>
            {% else %}
                <a class="nav-link" href="{% url 'users:login_user' %}">Войти</a>
                <a class="nav-link" href="{% url 'users:create_user' %}">Зарегистрироваться</a>
            {% endif %}
        </div>
    </div>
</nav>